# Site settings
title: Test GitHub Pages
email: your-email@domain.com
description: A test of GitHub Pages functionality using jekyll.
baseurl: "/test-gh-pages" # the subpath of your site, e.g. /blog

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
